name: flutter_firsts
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/Pic1.png
    - assets/Images/Pic2.webp
    - assets/Images/Pic3.jpg
    - assets/Images/Pic4.png
    - assets/Images/Pic5.png
